//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleClub.Tasks.PaymentTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomersView
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public int ReferrerId { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> CreatedAtDay { get; set; }
        public Nullable<int> CreatedAtMonth { get; set; }
        public Nullable<int> CreatedAtYear { get; set; }
        public Nullable<System.DateTime> CancelledDate { get; set; }
        public Nullable<int> CancelledDay { get; set; }
        public Nullable<int> CancelledMonth { get; set; }
        public Nullable<int> CancelledYear { get; set; }
    }
}
