//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleClub.Tasks.PaymentTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoicesView
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public int SiteId { get; set; }
        public int ReferrerId { get; set; }
        public decimal Amount { get; set; }
        public string StatusId { get; set; }
        public Nullable<System.DateTime> BilledDate { get; set; }
        public Nullable<int> BilledDay { get; set; }
        public Nullable<int> BilledMonth { get; set; }
        public Nullable<int> BilledYear { get; set; }
        public Nullable<System.DateTime> RefundedDate { get; set; }
        public Nullable<int> RefundedDay { get; set; }
        public Nullable<int> RefundedMonth { get; set; }
        public Nullable<int> RefundedYear { get; set; }
    }
}
