//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleClub.Tasks.PaymentTask
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referrer
    {
        public Referrer()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string URL { get; set; }
        public string SiteKey { get; set; }
        public string SiteIdentifier { get; set; }
        public string SiteValidator { get; set; }
        public string PostBackURL { get; set; }
        public int BilledTotal { get; set; }
        public decimal RefundAmount { get; set; }
        public decimal RevenueAmount { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
    }
}
