//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleClub.BusinessLogic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CastleClub.BusinessLogic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///&lt;body&gt;
        /// &lt;p&gt;Hello, you’ve sent a “forgot password” request.  You can update your password by clicking on the link below:&lt;/p&gt;
        /// &lt;p&gt;{0} &lt;/p&gt;
        /// &lt;p&gt;Thank you!&lt;/p&gt;
        /// &lt;p&gt;Customer Service {1} &lt;/p&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string SetPasswordBodyEmail {
            get {
                return ResourceManager.GetString("SetPasswordBodyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget password in {0}.
        /// </summary>
        internal static string SetPasswordSubjectEmail {
            get {
                return ResourceManager.GetString("SetPasswordSubjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;body&gt;&lt;p&gt;Hello {0},&lt;/p&gt;&lt;br/&gt;&lt;p&gt;Welcome to {3}!  We are pleased to confirm your {4} Membership to America&apos;s Leading Shopping Discount Club.&lt;/p&gt;&lt;p&gt;To access your members only benefits and special savings, simply follow the instructions below.&lt;/p&gt;&lt;ol&gt;&lt;li&gt;Visit &lt;a href=&apos;http://{10}&apos; style=&apos;color:rgb(15,105,151)&apos;&gt;&lt;b&gt;{10}&lt;/b&gt;&lt;/a&gt;&lt;/li&gt;&lt;li&gt;Log into our &apos;members only&apos; area using your login information below&lt;/li&gt;&lt;li&gt;Update or change your password&lt;/li&gt;&lt;li&gt;Choose from thousands of {4} Member discounts, benefits a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WelcomeBodyEmail {
            get {
                return ResourceManager.GetString("WelcomeBodyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        internal static string WelcomeSubjectEmail {
            get {
                return ResourceManager.GetString("WelcomeSubjectEmail", resourceCulture);
            }
        }
    }
}
