//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CastleClub.Tool.ModifyPassword.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Site
    {
        public Site()
        {
            this.Customers = new HashSet<Customer>();
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string AltNames { get; set; }
        public string Subtitle { get; set; }
        public string SignupDomain { get; set; }
        public string OfferDomain { get; set; }
        public decimal PricePerQuarter { get; set; }
        public string GroupId { get; set; }
        public string AuthorizeLoginId { get; set; }
        public string AuthorizeTransactionKey { get; set; }
        public bool MasterCardFullForm { get; set; }
        public bool Active { get; set; }
        public string Phone { get; set; }
        public string OfficeHours { get; set; }
        public string CSSOuterColor { get; set; }
        public string CSSBlueColor { get; set; }
        public string CSSEmphasizeColor { get; set; }
        public string ParticipatingPropertiesLogos { get; set; }
        public string BusinessSector { get; set; }
        public string LastUpdate { get; set; }
        public string Benefits { get; set; }
        public string WeHaveAmassed { get; set; }
        public int TotalVisits { get; set; }
        public string MailAddress { get; set; }
        public string ShortName { get; set; }
        public string Email { get; set; }
        public decimal Price { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
